### ISSUE TITLE
图因同源策略无法显示

### ISSUE THREAD

**Issue by Cirn09** [nulla2011/nulla2011.github.io#1]
浏览器：edge
比如https://nulla2011.github.io/2021/01/26/compose-full-watermelon
![image](https://user-images.githubusercontent.com/25722111/167613181-aabbe062-9a24-4178-ac1b-779beb8b1776.png)

**Comment by nulla2011** [comment]
还没来得及迁移图床，~~因为懒~~

**Comment by nulla2011** [comment]
dcd0365d51264f47e2ca0cb22711d3501ff87e81 已修复
